### ISSUE TITLE
Wine detection

### ISSUE THREAD

**Issue by stuta** [Egor-Skriptunoff/pure_lua_alert#1]
Great library but does not seem to work under wine (https://wine-staging.com) in OSX.

**Comment by Egor-Skriptunoff** [comment]
Thanks for bugreport.  
Wine support added in version 2.  Tested on Wine for Linux.  
Does it work now on Wine for OSX?

**Comment by stuta** [comment]
No, it does not.

print("windows_ver: "..windows_ver)
->
windows_ver: 
Microsoft Windows 6.1.7601 (1.9.4)

This is how I detect wine in luajit, but it may not be good for this project:

```
local hntdll = C.GetModuleHandleA(ffi.cstr("ntdll.dll"))
local pwine_get_version = C.GetProcAddress(hntdll, ffi.cstr("wine_get_version"))
if pwine_get_version ~= nil then
    isWine_l = true
    local ntdll = ffi.load("ntdll")
    if option then
        local vrs = ffi.string(ntdll.wine_get_version())
        print(" Wine version: '"..vrs.."'")
    end
else
    isWine_l = false
end
```

**Comment by Egor-Skriptunoff** [comment]
Wine detection fixed in version 3.

**Comment by stuta** [comment]
In my machine call_echo == "^^". 

If I fix it then all windows under Wine are very big and fonts seem small.

**Comment by Egor-Skriptunoff** [comment]
> all windows under Wine are very big

Yes, I said about that in README.
"mode" utility is absent in Wine, that's why there is no control over console window size, so all alert boxes are 80x25.
Unfortunately, Wine never was a good replacement for Windows.

> In my machine call_echo == "^^"

Are you sure?
I tested on Wine 1.6.2 for Linux and Wine 1.9.9 for Mac OS X, both give "^".
Please check it one more time.  I just cannot believe your system works that way.

If your system is really so strange, please try another solution (does it work for you?):
`is_wine = io.popen[[cmd /d/c "echo "^^""]]:read"*a":find"%^^"`

**Comment by stuta** [comment]
Sorry, I didn't re-read the readme.

is_wine = io.popen[[cmd /d/c "echo "^^""]]:read"*a":find"%^^"
-> result is_wine: 2

In osx teminal: 
wine cmd /d/c "echo "^^""
-> result is: ^ (without quotes)

In win7:
cmd /d/c "echo "^^""
-> result is: "^" (with quotes)

I use https://wine-staging.com with msys2 and mingw installed.

**Comment by Egor-Skriptunoff** [comment]
> is_wine = io.popen[[cmd /d/c "echo "^^""]]:read"*a":find"%^^"
> -> result is_wine: 2

OK, second solution does work for you.
I've updated the code.

**Comment by stuta** [comment]
Thanks!

This is VERY cool library and useful for displaying critical messages that do not block main program.
